// apps/frontend/src/lib/components/ControlsList.svelte
<script lang="ts">
  import { fly } from "svelte/transition";

  export let isVertical = false;
  export let shiftUp = false;
  export let shiftRight = false;
</script>

<ul
  in:fly={{ duration: 250, x: !isVertical ? -50 : 0, y: isVertical ? 50 : 0 }}
  class="pointer-events-none fixed flex gap-2"
  class:flex-col-reverse={isVertical}
  class:bottom-24={shiftUp}
  class:bottom-8={!shiftUp}
  class:left-24={shiftRight}
  class:left-8={!shiftRight}
>
  <slot />
</ul>

// apps/frontend/src/lib/react/components/ControlsList.tsx
export default function ControlsList({
  isVertical = false,
  shiftUp = false,
  shiftRight = false,
  children,
}: {
  isVertical?: boolean;
  shiftUp?: boolean;
  shiftRight?: boolean;
  children: React.ReactNode;
}) {
  return (
    <ul
      className={`
        pointer-events-none fixed flex animate-[fade-in_0.25s] gap-2
        ${
          isVertical
            ? "animate-[fly-up_0.25s] flex-col-reverse"
            : "animate-[fly-right_0.25s]"
        }
        ${shiftUp ? "bottom-24" : "bottom-8"}
        ${shiftRight ? "left-24" : "left-8"}
      `}
    >
      {children}
    </ul>
  );
}
